### PR TITLE
Add EFS in Terraform, add helm config for efs-provisioner, and restru…

### PR DESCRIPTION
**Pull request by salvadorcruz10**
Add EFS in terraform, add helm config for efs-provisioner and structure files' order in repo.

Signed-off-by: salvador.cruz <salvador.cruz@oportun.com>

### CODE REVIEW

**Review by fbuenowizeline — APPROVED** [review]
Approved

**Comment by fbuenowizeline** [comment]
Approved

**Review by IsFlwrs — APPROVED** [review]
LGTM 👍

**Review by IsFlwrs — APPROVED** [review]
LGTM 👍

**Review by IsFlwrs — APPROVED** [review]

**Pull request merged**
